# Basic
title: MengAi's Blog
subtitle: 做最好的自己！
welcome_message: 移动开发经验记录和分享.
description: 嗨，iOS & RN开发，顺带写写小程序，坐标杭州。
#creator: <a href="http://onev.cat">@onevcat</a>

url: "https://github.com/mengai123"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: 文章
    description: 文章列表

# Navigation buttons in the front page.
nav:
    - {title: GitHub主页, description: GitHub主页, url: 'https://github.com/mengai123'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
#    weibo: onevcat
    github: mengai123
#    twitter: onevcat
#    gplus: 107108267983477358170
    mail: 762614600@qq.com

# Google Analytics
#ga:
    # id: your_ga_id
    # host: your_host
